### ISSUE TITLE
ChefStyle/UnnecessaryPlatformCaseStatement crashes if the when has no content

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#497]
This crashes cookstyle:

```ruby
case node['platform']
when 'ubuntu'
  #  default['opencv']['repository'] = "ppa"
end
```

```
undefined method `multiline?' for nil:NilClass
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/style/unnecessary_platform_case_statement.rb:67:in `block (2 levels) in autocorrect'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/style/unnecessary_platform_case_statement.rb:67:in `platform_case?'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/style/unnecessary_platform_case_statement.rb:62:in `block in autocorrect'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/cop.rb:36:in `call'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/corrector.rb:63:in `block (2 levels) in rewrite'
/usr/local/lib/ruby/gems/2.6.0/gems/parser-2.7.0.1/lib/parser/source/tree_rewriter.rb:220:in `transaction'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/corrector.rb:62:in `block in rewrite'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/corrector.rb:60:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/corrector.rb:60:in `rewrite'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:131:in `autocorrect_all_cops'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:72:in `autocorrect'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:103:in `block in offenses'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:120:in `investigate'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:99:in `offenses'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:283:in `inspect_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:231:in `block in do_inspection_loop'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:263:in `block in iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:256:in `loop'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:256:in `iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:227:in `do_inspection_loop'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:124:in `block in file_offenses'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:142:in `file_offense_cache'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:122:in `file_offenses'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:110:in `process_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `reduce'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:73:in `inspect_files'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:39:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:210:in `execute_runner'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:80:in `execute_runners'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:51:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/exe/rubocop:12:in `<top (required)>'
../work/cookstyle/bin/cookstyle:21:in `load'
../work/cookstyle/bin/cookstyle:21:in `<main>'
```

**Comment by tas50** [comment]
No longer an issue in master
