### ISSUE TITLE
ChefDeprecations/WindowsTaskChangeAction crashes if action is not a symbol

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#498]
If the action is set via a variable this cop crashes:

```
undefined method `value' for :action_option:Symbol
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:76:in `check_action'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:54:in `block (2 levels) in on_block'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:54:in `each'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:54:in `block in on_block'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:59:in `block (2 levels) in match_property_in_resource?'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:116:in `block (2 levels) in extract_send_types'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:112:in `extract_send_types'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:116:in `block in extract_send_types'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:116:in `each'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:116:in `extract_send_types'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:58:in `block in match_property_in_resource?'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:57:in `each'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/chef/cookbook_helpers.rb:57:in `match_property_in_resource?'
/Users/tsmith/dev/work/cookstyle/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:48:in `on_block'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:128:in `with_cop_error_handling'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:55:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:32:in `block (2 levels) in <class:Commissioner>'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:100:in `on_def'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:50:in `block in on_begin'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:50:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:50:in `on_begin'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:13:in `walk'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:44:in `investigate'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:119:in `investigate'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:99:in `offenses'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:283:in `inspect_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:231:in `block in do_inspection_loop'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:263:in `block in iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:256:in `loop'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:256:in `iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:227:in `do_inspection_loop'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:124:in `block in file_offenses'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:142:in `file_offense_cache'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:122:in `file_offenses'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:110:in `process_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `reduce'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:73:in `inspect_files'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:39:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:210:in `execute_runner'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:80:in `execute_runners'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:51:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/exe/rubocop:12:in `<top (required)>'
../work/cookstyle/bin/cookstyle:21:in `load'
../work/cookstyle/bin/cookstyle:21:in `<main>'
```

```ruby
 windows_task task do

    if action_option
      action action_option
    end
end
```

**Comment by tas50** [comment]
Fixed by #531
