### ISSUE TITLE
ChefStyle/UnnecessaryPlatformCaseStatement breaks rspec tests

### ISSUE THREAD

**Issue by Xorima** [chef/cookstyle#500]
# Version:

docker chef/chefworkstation: latest

# Environment:

https://github.com/sous-chefs/apache2/pull/669

# Scenario:

`cookstyle -a`

# Steps to Reproduce:

`cookstyle -a`

# Expected Result:

tests continue to function

# Actual Result:

code:
```
require 'spec_helper'

RSpec.describe Apache2::Cookbook::Helpers do
  class DummyClass < Chef::Node
    include Apache2::Cookbook::Helpers
  end

  subject { DummyClass.new }

  describe '#default_cache_root' do
    before do
      allow(subject).to receive(:[]).with('platform_family').and_return(platform_family)
    end

    context 'with rhel family' do
      let(:platform_family) { 'rhel' }

      it 'returns the correct path' do
        expect(subject.default_cache_root).to eq '/var/cache/httpd/mod_cache_disk'
      end
    end

    context 'with fedora family' do
      let(:platform_family) { 'fedora' }

      it 'returns the correct path' do
        expect(subject.default_cache_root).to eq '/var/cache/httpd/mod_cache_disk'
      end
    end

    context 'with amazon family' do
      let(:platform_family) { 'amazon' }

      it 'returns the correct path' do
        expect(subject.default_cache_root).to eq '/var/cache/httpd/mod_cache_disk'
      end
    end

    context 'with SUSE family' do
      let(:platform_family) { 'suse' }

      it 'returns the correct path' do
        expect(subject.default_cache_root).to eq '/var/cache/apache2/proxy'
      end
    end

    context 'with Debian' do
      let(:platform_family) { 'debian' }
      it 'returns the correct path' do
        expect(subject.default_cache_root).to eq '/var/cache/apache2/proxy'
      end
    end

    context 'with arch' do
      let(:platform_family) { 'arch' }
      it 'returns the correct path' do
        expect(subject.default_cache_root).to eq '/var/cache/httpd/mod_cache_disk'
      end
    end

    context 'with freebsd' do
      let(:platform_family) { 'freebsd' }
      it 'returns the correct path' do
        expect(subject.default_cache_root).to eq '/var/cache/apache24/proxy'
      end
    end
  end
end
```

starts throwing the following errors:
```
  7) Apache2::Cookbook::Helpers#default_cache_root with freebsd returns the correct path
     Failure/Error: expect(subject.default_cache_root).to eq '/var/cache/apache24/proxy'
     
       #<DummyClass:0x00000000050b0fb8 @chef_server_rest=nil, @name=nil, @logger=#<Mixlib::Log::Child:0x00000000050b0f40 @parent=Chef::Log, @metadata={:subsystem=>"node"}>, @chef_environment="_default", @primary_runlist=#<Chef::RunList:0x00000000050b0ef0 @run_list_items=[]>, @override_runlist=#<Chef::RunList:0x00000000050b0e78 @run_list_items=[]>, @policy_name=nil, @policy_group=nil, @attributes=#<Chef::Node::Attribute @default={}, @env_default={}, @role_default={}, @force_default={}, @normal={}, @override={}, @role_override={}, @env_override={}, @force_override={}, @automatic={}, @merged_attributes=nil, @properties=nil>, @run_state={}> received :[] with unexpected arguments
         expected: ("platform_family")
              got: (:platform_family)
       Diff:
       @@ -1,2 +1,2 @@
       -["platform_family"]
       +[:platform_family]
       
        Please stub a default value first if message might be received with other args as well. 
     # ./libraries/helpers.rb:170:in `default_cache_root'
     # ./spec/libraries/cache_root_spec.rb:64:in `block (4 levels) in <top (required)>'

Finished in 29.21 seconds (files took 4.29 seconds to load)
252 examples, 7 failures

Failed examples:

rspec ./spec/libraries/cache_root_spec.rb:18 # Apache2::Cookbook::Helpers#default_cache_root with rhel family returns the correct path
rspec ./spec/libraries/cache_root_spec.rb:26 # Apache2::Cookbook::Helpers#default_cache_root with fedora family returns the correct path
rspec ./spec/libraries/cache_root_spec.rb:34 # Apache2::Cookbook::Helpers#default_cache_root with amazon family returns the correct path
rspec ./spec/libraries/cache_root_spec.rb:42 # Apache2::Cookbook::Helpers#default_cache_root with SUSE family returns the correct path
rspec ./spec/libraries/cache_root_spec.rb:49 # Apache2::Cookbook::Helpers#default_cache_root with Debian returns the correct path
rspec ./spec/libraries/cache_root_spec.rb:56 # Apache2::Cookbook::Helpers#default_cache_root with arch returns the correct path
rspec ./spec/libraries/cache_root_spec.rb:63 # Apache2::Cookbook::Helpers#default_cache_root with freebsd returns the correct path
```

**Comment by afiune** [comment]
@Xorima Thank you for reporting this bug, could you help us providing the version of Chef Workstation (`chef -v`)?

**Comment by Xorima** [comment]
@afiune `Cookstyle version: 5.16.11`

**Comment by tas50** [comment]
There's not really a way around this one. Modernizing cookbooks is always going to risk breaking existing specs that check for usage of old helpers or node attributes.
