### ISSUE TITLE
actions blow up if computed elsewhere for ChefDeprecations/WindowsTaskChangeAction

### ISSUE THREAD

**Issue by Xorima** [chef/cookstyle#519]
# Version:

```
Cookstyle 5.20.0
  * RuboCop 0.75.1
```

# Environment:

Windows 10, WSL running workstation

```
Chef Workstation version: 0.15.18
Chef Infra Client version: 15.7.32
Chef InSpec version: 4.18.51
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.20.0
```

# Scenario:

Run `cookstyle`

# Steps to Reproduce:

Create a recipe with these contents:

```ruby
action = dirs.include?('foo') || dirs.include?('bar') ? :create : :delete
windows_task 'only create if foo or bar exists, else delete' do
  user        'myaccount'
  password    'Password123'
  command     "powershell.exe -ExecutionPolicy Bypass -File #{script_file}"
  frequency   :daily
  start_time  '00:00'
  action      action
end
```

# Expected Result:

it to not blow up

# Actual Result:

```bash
An error occurred while ChefDeprecations/WindowsTaskChangeAction cop was inspecting test.rb:2:0.
undefined method `value' for :action:Symbol
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:76:in `check_action'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:54:in `block (2 levels) in on_block'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:54:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:54:in `block in on_block'      
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/chef/cookbook_helpers.rb:59:in `block (2 levels) in match_property_in_resource?'  
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/chef/cookbook_helpers.rb:112:in `extract_send_types'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/chef/cookbook_helpers.rb:58:in `block in match_property_in_resource?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/chef/cookbook_helpers.rb:57:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/chef/cookbook_helpers.rb:57:in `match_property_in_resource?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb:48:in `on_block'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:128:in `with_cop_error_handling'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:55:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:32:in `block (2 levels) in <class:Commissioner>'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:50:in `block in on_begin'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:50:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:50:in `on_begin'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/ast/traversal.rb:13:in `walk'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/commissioner.rb:44:in `investigate'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:119:in `investigate'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:107:in `offenses'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:283:in `inspect_file'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:231:in `block in do_inspection_loop'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:263:in `block in iterate_until_no_changes'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:256:in `loop'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:256:in `iterate_until_no_changes'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:227:in `do_inspection_loop'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:124:in `block in file_offenses'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:142:in `file_offense_cache'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:122:in `file_offenses'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:110:in `process_file'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `reduce'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:73:in `inspect_files'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/runner.rb:39:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:210:in `execute_runner'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:80:in `execute_runners'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/lib/rubocop/cli.rb:51:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/exe/rubocop:13:in `block in <top (required)>'
/opt/chef-workstation/embedded/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/rubocop-0.75.1/exe/rubocop:12:in `<top (required)>'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/bin/cookstyle:21:in `load'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/cookstyle-5.20.0/bin/cookstyle:21:in `<top (required)>'
/usr/bin/cookstyle:361:in `load'
/usr/bin/cookstyle:361:in `<main>'
```

**Comment by afiune** [comment]
Thanks for reporting this bug, this is a good first issue to contribute and we would love to have contributions, otherwise, we will prioritize this accordingly.

**Comment by tas50** [comment]
This was a dupe of https://github.com/chef/cookstyle/issues/498, but they're both fixes now.
