### ISSUE TITLE
chefspec - undefined method shell_out' - aftercookstyle -a`

### ISSUE THREAD

**Issue by snehaldwivedi** [chef/cookstyle#873]
reference issue https://github.com/chef/customer-bugs/issues/300

# Version:

[Version of the project installed]

# Environment:

[Details about the environment such as the Operating System, cookbook details, etc...]

# Scenario:

Cookstyle auto correcting Mixlib::ShellOut.new(cmd).run_command to shell_out(cmd) and inspec is failing with undefined method `shell_out'

Cookstyle autocorrected as follows.

`$ chef exec cookstyle -aInspecting 6 files...R..Offenses:lib/windjammer/deployer.rb:123:13: R: [Corrected] Chef/Modernize/ShellOutHelper: Use the built-in shell_out helper available in Chef Infra Client 12.11+ instead of calling Mixlib::ShellOut.new('foo').run_command. res = Mixlib::ShellOut.new(cmd).run_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^6 files inspected, 1 offense detected, 1 offense corrected`

Where the change:

`$ git diffdiff --git a/lib/windjammer/deployer.rb b/lib/windjammer/deployer.rbindex 4dab5dc..b7ec1b8 100644--- a/lib/windjammer/deployer.rb+++ b/lib/windjammer/deployer.rb@@ -120,7 +120,7 @@ class Windjammer def run_step(id, step, params) cmd = "run_step --id=#{id} --name=#{step} --params='#{params.to_json}'"- res = Mixlib::ShellOut.new(cmd).run_command+ res = shell_out(cmd) fail "Command Failed with #{res.exitstatus}" unless res.exitstatus.zero? end end`

ChefSpec starts to fail with the undefined method `shell_out'.

` $ chef exec rspecFFF.Failed to get JSON: Caught error response: 404 # このエラーは謎なのですが関係ないとおもいます。.Failed to get JSON: Caught error response: 404Failed to get JSON: Caught error response: 404Failed to get JSON: Caught error response: 404Failed to get JSON: Caught error response: 404Failed to get JSON: Caught error response: 404...FFFailures: 1) Windjammer::Deployer down status Failure/Error: res = shell_out(cmd) NoMethodError: undefined method `shell_out' for #<Windjammer::Deployer:0x00000000014bb300> # ./lib/windjammer/deployer.rb:123:in `run_step' # ./lib/windjammer/deployer.rb:27:in `down' # ./spec/unit/windjammer/deployer_spec.rb:71:in `block (2 levels) in <top (required)>'`

Please advise us on how to change the chef spec to make it pass.

Unfortunately, the chef spec content cannot be shared due to customer policy so please tell us what should be included when testing `shell_out` with chef spec.

# Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem?]

# Expected Result:

After cookstyle auto correcting `Mixlib::ShellOut.new(cmd).run_command` to `shell_out(cmd)` and inspec is failing with undefined method `shell_out`

# Actual Result:

ChefSpec should respect the change and should have `shell_out(cmd)` as a defined method.

**Comment by tas50** [comment]
@lamont-granquist is this something we need to fix on the chefspec side or does this simply require a stub of the shell_out command?

**Comment by snehaldwivedi** [comment]
@tas50 I tried it stubbing but somehow it's not recognizing `shell_out` so I am still looking into chefspec how to fix it

```An error occurred while loading ./spec/cookstyle_test_spec.rb.
Failure/Error: require '/home/msys/cookbooks/testing_cookbooks/recipes/cookstyle_test'

NoMethodError:
  undefined method `shellout' for main:Object
# ./recipes/cookstyle_test.rb:3:in `<top (required)>'
# ./spec/cookstyle_test_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00007 seconds (files took 0.32159 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by snehaldwivedi** [comment]
@lamont-granquist @tas50 adding `require 'mixlib/shellout'` & `include Chef::Mixin::ShellOut` in our recipe and adding `require "chef/mixin/shell_out"` in spec I am able to solve this issue.  Following are the steps I followed 

$ cat recipes/default.rb 
```
require 'mixlib/shellout'
include Chef::Mixin::ShellOut

find = Mixlib::ShellOut.new("echo 'hostname -I'").run_command
find.stdout 

```
$ cat spec/default_spec.rb 

```
require "chef/mixin/shell_out"

describe 'first_cookbook::default' do
  let(:shell_out) do
    Mixlib::ShellOut.new("hostname -I")
  end

  it 'converges successfully' do
    expect(shell_out.run_command.stdout).to eq("172.31.23.200 \n")
  end
end
```

after running `cookstyle -a  recipes/default.rb` it update rescipe as follows 

$ cat recipes/default.rb 
```
require 'mixlib/shellout'
include Chef::Mixin::ShellOut

find = shell_out("echo 'hostname -I'")
find.stdout
```

```
first_cookbook$ chef exec rspec spec/default_spec.rb 
.

Finished in 0.0053 seconds (files took 0.23171 seconds to load)
1 example, 0 failures
```

Please confirm if this can be the solution we can suggest to the customer?

**Comment by snehaldwivedi** [comment]
closing as per [comment](https://github.com/chef/customer-bugs/issues/300#issuecomment-937427986).
